stages:
  - install
  - test

composer:
  stage: install
  image: composer:latest
  artifacts:
    when: on_success
    paths:
      - ./vendor/
  script:
    - "composer update -a --prefer-dist --no-suggest --no-scripts --ignore-platform-reqs"

test:7.0:
  image: php:7.0
  dependencies:
    - composer
  script:
    - "tester test -s"
  when: always

test:7.1:
  image: php:7.1
  dependencies:
    - composer
  script:
    - "tester test -s"
  when: always

test:7.2:
  image: php:7.2
  dependencies:
    - composer
  script:
    - "tester test -s"
  when: always