stages:
  - install
  - test

composer:
  stage: install
  image: composer:latest
  artifacts:
    expire_in: 5 mins
    when: on_success
    paths:
      - ./vendor/
  script:
    - "composer install -a --prefer-dist --no-suggest --no-scripts --ignore-platform-reqs --no-progress"

test:
  image: registry.gitlab.litea.cz/images/php/7.3-fpm-alpine/dev:v2.5.1
  dependencies:
    - composer
  script:
    - php ./vendor/bin/phpunit --colors=never
  when: always
