before_script:
 - "composer update -a --prefer-dist --no-suggest --no-scripts --ignore-platform-reqs"


test:7.0:
  image: php:7.0
  script:
    - "tester test -s"
  when: always

test:7.1:
  image: php:7.1
  script:
    - "tester test -s"
  when: always

test:7.2:
  image: php:7.2
  script:
    - "tester test -s"
  when: always